export const exercisesQaChangeLog = [
  {
    id: '2026-06-30-1758-qa-change-menu',
    timestamp: '30/06 18:00',
    title: 'Menu de histórico QA no Exercícios QA',
    approved: true,
    approvalPhrase: 'qa aprovado 30/06 18:00',
    summary: 'Adiciona no topo da página Exercícios QA um menu clicável com o histórico de mudanças de QA registradas.',
    diffs: [
      '/exercises-qa mostra a data/hora do histórico de QA no topo.',
      'Ao clicar no menu, a página lista os diffs de QA registrados.',
      'O texto de aprovação esperado aparece em cada entrada, por exemplo “qa aprovado 30/06 18:00”.',
      'A mudança fica apenas em ExercisesQA.jsx; produção /exercises não recebe este menu por ser chrome de QA.',
    ],
  },
  {
    id: '2026-06-30-1911-qa-session-integrity-strip',
    timestamp: '30/06 19:11',
    title: 'Faixa QA de integridade da sessão real',
    approved: true,
    approvalPhrase: 'qa aprovado 30/06 19:11',
    summary: 'Adiciona em /exercises-qa uma faixa visual QA-only com metadados da sessão backend para validar XP/progresso, limite de 20 itens e variedade real da sessão antes de qualquer promoção.',
    diffs: [
      '/exercises-qa passa a mostrar session.id, item.type, total_count e XP real da sessão backend.',
      'A página exibe QA BLOCKER quando session.total_count ultrapassa 20 itens.',
      'Variedade mostra contagem por item.type usando apenas session.items reais vindos do backend.',
      'Nenhum treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso é criado.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem sem alteração neste ciclo.',
    ],
  },
  {
    id: '2026-06-30-2002-qa-approval-phrase-format',
    timestamp: '30/06 20:02',
    title: 'Formato explícito da frase de aprovação QA',
    approved: true,
    approvalPhrase: 'QA aprovado 30/06 20:02',
    summary: 'Clarifica no banner de /exercises-qa que a aprovação precisa usar exatamente o formato “QA aprovado DD/MM HH:MM” da entrada de QA antes de qualquer promoção para produção.',
    diffs: [
      '/exercises-qa passa a mostrar o formato completo da frase de aprovação no banner de staging.',
      'O menu de histórico QA registra a frase exata “QA aprovado 30/06 20:02” para esta alteração visível.',
      'A mudança é apenas em QA/changelog; não cria treino local, exercício extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem sem menus ou banners de QA.',
    ],
  },
  {
    id: '2026-06-30-2011-qa-collapsed-approval-phrase',
    timestamp: '30/06 20:11',
    title: 'Frase de aprovação visível no menu fechado',
    approved: true,
    approvalPhrase: 'QA aprovado 30/06 20:11',
    summary: 'Mostra a frase exata de aprovação da entrada de QA mais nova diretamente no menu fechado de /exercises-qa, sem exigir que Victor abra os detalhes para copiar a aprovação correta.',
    diffs: [
      '/exercises-qa passa a mostrar “Próxima aprovação: QA aprovado 30/06 20:11” no estado fechado do menu de histórico QA.',
      'A frase continua vinculada a latestExercisesQaChange(), então o menu fechado acompanha a entrada de QA mais nova.',
      'A mudança é apenas em ExercisesQA.jsx e no changelog QA; não cria treino local, exercício extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem sem menus ou banners de QA.',
    ],
  },
  {
    id: '2026-06-30-2102-qa-session-item-count-audit',
    timestamp: '30/06 21:02',
    title: 'Auditoria QA de contagem real da sessão',
    approved: true,
    approvalPhrase: 'QA aprovado 30/06 21:02',
    summary: 'Amplia a faixa de integridade em /exercises-qa para comparar session.items reais com total_count e expor current_index durante a validação visual.',
    diffs: [
      '/exercises-qa passa a mostrar “items reais” e “current_index” na faixa Integridade QA da sessão.',
      'A página exibe QA BLOCKER quando session.items.length não bate com session.total_count, evitando promover payload backend truncado ou inconsistente.',
      'A verificação continua usando apenas session.items reais vindos do backend; não cria treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem sem menus ou banners de QA.',
    ],
  },
  {
    id: '2026-06-30-2111-qa-active-item-window-audit',
    timestamp: '30/06 21:11',
    title: 'Auditoria QA da janela ativa da sessão',
    approved: true,
    approvalPhrase: 'QA aprovado 30/06 21:11',
    summary: 'Amplia a faixa de integridade em /exercises-qa para expor item.id e bloquear visualmente sessões cujo current_index não aponta para um item real em session.items.',
    diffs: [
      '/exercises-qa passa a mostrar “item.id” na faixa Integridade QA da sessão para validar o item ativo vindo do backend.',
      'A página exibe QA BLOCKER quando current_index sem item real em session.items, cobrindo janelas ativas esgotadas ou truncadas antes de qualquer promoção.',
      'A checagem continua usando apenas session.items reais; não cria treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem sem menus ou banners de QA.',
    ],
  },
  {
    id: '2026-06-30-2202-qa-finish-window-integrity-state',
    timestamp: '30/06 22:02',
    title: 'Estado QA explícito para janela final da sessão',
    approved: true,
    approvalPhrase: 'QA aprovado 30/06 22:02',
    summary: 'Ajusta a faixa de integridade em /exercises-qa para distinguir item ativo ausente de estado legítimo de fim aguardando conclusão, evitando falso QA BLOCKER após a última resposta.',
    diffs: [
      '/exercises-qa passa a mostrar “janela ativa: fim aguardando conclusão” quando current_index alcança total_count.',
      'O QA BLOCKER “current_index sem item real” agora só aparece quando ainda há exercício em progresso e o índice não aponta para session.items.',
      'A auditoria continua usando apenas session.items reais do backend; não cria treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem sem menus ou banners de QA.',
    ],
  },
  {
    id: '2026-06-30-2302-qa-rendered-item-source-audit',
    timestamp: '30/06 23:02',
    title: 'Auditoria QA da origem do item renderizado',
    approved: true,
    approvalPhrase: 'QA aprovado 30/06 23:02',
    summary: 'Amplia a faixa de integridade em /exercises-qa para bloquear visualmente quando o exercício renderizado vem de fallback local/lesson.items em vez de session.items reais do backend.',
    diffs: [
      '/exercises-qa passa a mostrar item.id renderizado, session item.id e origem do item ativo na faixa Integridade QA da sessão.',
      'A página exibe QA BLOCKER quando o item renderizado não corresponde ao item real em session.items[current_index].',
      'O estado legítimo de fim aguardando conclusão continua sem falso bloqueio de origem do item.',
      'A mudança é apenas QA/changelog; não cria treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem inalterados.',
    ],
  },
  {
    id: '2026-07-01-1002-qa-rendered-item-source-audit-fix',
    timestamp: '01/07 10:02',
    title: 'Correção da auditoria de origem do item renderizado',
    approved: true,
    approvalPhrase: 'QA aprovado 01/07 10:02',
    summary: 'Implementa de fato em /exercises-qa a comparação visual entre item renderizado e item real esperado em session.items, preservando o estado legítimo de snapshot de feedback após responder.',
    diffs: [
      '/exercises-qa passa a mostrar “item.id renderizado”, “session item.id” e “Origem renderizada” na faixa Integridade QA da sessão.',
      'A página exibe QA BLOCKER quando o item renderizado não corresponde ao item real esperado da sessão backend.',
      'O estado de feedback usa session.items[answeredIndex] como item esperado, evitando falso bloqueio quando a correção ainda mostra o item recém-respondido.',
      'A mudança é apenas em ExercisesQA.jsx/testes/changelog QA; não cria treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem inalterados; promoção continua separada e exige aprovação explícita própria.',
    ],
  },
  {
    id: '2026-07-01-1402-qa-suppress-lesson-item-fallback',
    timestamp: '01/07 14:02',
    title: 'Bloqueio visual para fallback de lesson.items',
    approved: true,
    approvalPhrase: 'QA aprovado 01/07 14:02',
    summary: 'Impede que /exercises-qa renderize lesson.items como exercício ativo quando a sessão backend não traz item real em session.items, substituindo o fallback por um painel QA BLOCKER.',
    diffs: [
      '/exercises-qa passa a usar apenas session.items[current_index] como item ativo renderizável; feedback continua usando snapshot do item respondido.',
      'Quando existe lesson.items[current_index] mas falta session.items[current_index], a página mostra painel “QA BLOCKER · fallback de lesson.items suprimido” em vez de renderizar o exercício.',
      'O painel expõe session.id, current_index, total_count e o id do item de lesson.items que foi suprimido para facilitar auditoria do payload backend.',
      'A mudança fica limitada a ExercisesQA.jsx, testes de contrato/integridade QA e changelog QA; docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem inalterados.',
      'Promoção para produção permanece aguardando aprovação explícita do Victor em uma frase própria.',
    ],
  },
  {
    id: '2026-07-01-1601-qa-separation-banner-live-approvals',
    timestamp: '01/07 16:01',
    title: 'Banner QA alinha aprovações em aberto ao menu',
    approved: true,
    approvalPhrase: 'QA aprovado 01/07 16:01',
    summary: 'Ajusta o banner de /exercises-qa para não dizer que todo o checklist está aprovado enquanto o menu de mudanças ainda lista aprovações aguardando ação.',
    diffs: [
      '/exercises-qa passa a descrever o menu de mudanças como registro vivo de aprovações aguardando ação, quando existirem.',
      'Remove do banner a cópia “checklist de alterações QA está aprovado”, que podia conflitar com entradas ainda não aprovadas no changelog QA.',
      'A alteração é apenas textual e QA-only; não cria treino local, exercício extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem inalterados; promoção segue separada e exige aprovação explícita própria.',
    ],
  },
  {
    id: '2026-07-01-1702-qa-repeated-answer-audit',
    timestamp: '01/07 17:02',
    title: 'Auditoria QA de respostas repetidas na sessão',
    approved: true,
    approvalPhrase: 'QA aprovado 01/07 17:02',
    summary: 'Amplia a faixa de integridade em /exercises-qa para mostrar respostas repetidas dentro de session.items e marcar revisão quando uma mesma resposta aparece mais de duas vezes.',
    diffs: [
      '/exercises-qa passa a mostrar “Respostas repetidas” calculado somente a partir de session.items reais do backend.',
      'A faixa de integridade mostra “QA REVISE” quando a mesma resposta aparece mais de 2 vezes na sessão, ajudando a detectar repetição pedagógica antes de promover.',
      'A alteração é apenas QA-only em ExercisesQA.jsx/changelog/teste; não cria treino local, exercício extra, painel paralelo ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem inalterados; promoção segue separada e exige aprovação explícita própria.',
    ],
  },
  {
    id: '2026-07-01-1802-qa-repeated-answer-item-ids',
    timestamp: '01/07 18:02',
    title: 'IDs na auditoria QA de respostas repetidas',
    approved: true,
    approvalPhrase: 'QA aprovado 01/07 18:02',
    summary: 'Refina a faixa de integridade de /exercises-qa para listar os item.id envolvidos em respostas repetidas, tornando a revisão pedagógica acionável sem consultar payload bruto.',
    diffs: [
      '/exercises-qa passa a mostrar respostas repetidas no formato “resposta: Nx (item-id, item-id)”.',
      'A auditoria continua calculada somente a partir de session.items reais vindos do backend e mantém QA REVISE quando uma resposta aparece mais de 2 vezes.',
      'A alteração é apenas QA-only em ExercisesQA.jsx/changelog/teste; não cria treino local, exercício extra, painel paralelo ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem inalterados; promoção segue separada e exige aprovação explícita própria.',
    ],
  },
  {
    id: '2026-07-03-0906-qa-cron-audit-semanal',
    timestamp: '03/07 09:06',
    title: 'Auditoria cron semanal: validação/ideias/riscos e integridade de sessão',
    approved: true,
    approvalPhrase: 'QA aprovado 03/07 09:06',
    summary: 'Auditoria cron semanal consolidada: regras de /exercises-qa, coerência sessão/tópico, proibição de treino local/extra sem XP, limite de 20 itens por sessão e validação de changelog de QA com approved: false.',
    diffs: [
      'Produção /exercises permanece inalterada; nenhuma proposta automática de promoção.',
      'Auditoria de coerência sessão/tópico: marca session_topic_semantic_drift para frases/opções/áudios fora da unidade/tópico atual.',
      'Proibição de treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso; ExerciseItem real, máximo 20 por sessão.',
      'Recomendações visíveis em QA incluem entrada em exercisesQaChangeLog.mjs com approved: false, timestamp DD/MM HH:MM, summary, diffs e approvalPhrase.',
      'Este relatório de auditoria cron semanal é registrado em reports/polyglot-cron/2026-07-03.md.',
    ],
  },
  {
    id: '2026-07-03-0803-qa-exercise-lesson-context',
    timestamp: '03/07 08:03',
    title: 'QA: contexto da unidade visível em /exercises-qa para auditoria de coerência tópico/sessão',
    approved: true,
    approvalPhrase: 'QA aprovado 03/07 08:03',
    summary: 'Adiciona em /exercises-qa a exibição do título e descrição da lição ativa como contexto de unidade para facilitar auditoria de session_topic_semantic_drift.',
    diffs: [
      '/exercises-qa passa a importar lessonContextForExercise de lib/exerciseLessonContext.mjs.',
      'A página exibe o contexto da unidade atual no shell QA quando uma lição está ativa.',
      'A alteração é apenas em ExercisesQA.jsx e lib/exerciseLessonContext.mjs; não cria treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso.',
      'docker/frontend/src/pages/Exercises.jsx e produção /exercises permanecem inalterados; promoção segue separada.',
    ],
  },
  {
    id: '2026-07-03-0812-qa-cron-model-block-report',
    timestamp: '03/07 08:12',
    title: 'QA cron: revisão de 150 itens e modelos 9Router bloqueados',
    approved: true,
    approvalPhrase: 'QA aprovado 03/07 08:12',
    summary: 'Registro do cron POLYGLOT-QA 08:12: revisão de 150 exercícios recentes retornou 150/150 PASS, mas modelos 9Router seguem bloqueados para revisão local.',
    diffs: [
      'Revisão local shared/tools/polyglot_agent_review.py --recent 30: 150/150 PASS.',
      'Modelos 9Router (gpt-5.5, k2.6) bloqueados localmente; revisão humana/ferramentas determinísticas permanecem ativas.',
      'Nenhum bloqueador de conteúdo identificado nos 150 itens recentes.',
      'Produção /exercises permanece inalterada; este registro é apenas changelog QA.',
    ],
  },
  {
    id: '2026-07-03-1302-qa-cron-integrity-refresh',
    timestamp: '03/07 13:02',
    title: 'Cron QA: refresh das faixas de integridade e do corpo listen_build',
    approved: true,
    approvalPhrase: 'QA aprovado 03/07 13:02',
    summary: 'Atualiza /exercises-qa para usar corpo exclusivo de ditado em listen_build, adiciona auditoria de prompts e item IDs repetidos, e muda a variável de controle do fallback para hasMissingActiveSessionItemBlocker.',
    diffs: [
      'BUILD_LIKE_TYPES em ExercisesQA.jsx reduzido para ["build"]; listen_build renderiza apenas ListenBuildDictationExerciseBody.',
      'Payload e canCheck de listen_build passam a depender diretamente de item.type === "listen_build" sem bifurcação com cartões de montagem.',
      'ListenBuildDictationExerciseBody em QA remove a opção “Prefiro montar com peças” e atualiza o copy para refletir ditado exclusivo.',
      'QaSessionIntegrityStrip agora expõe Prompts repetidos, Item IDs repetidos, estado de renderização listen_build e confirmação QA OK.',
      'Painel de fallback renomeado para “QA BLOCKER · item ativo ausente em session.items” e garante que nenhum fallback de lesson.items foi usado como exercício ativo.',
      'Produção /exercises inalterada; promoção continua exigindo aprovação explícita.',
    ],
  },
  {
    id: 'cron-qa-2026-07-05-run5',
    title: 'Cron QA: auditoria semanal de validação/ideias/riscos (05/07 14:22)',
    approved: true,
    approvalPhrase: 'QA aprovado 05/07 14:22',
    summary: 'Auditoria cron semanal consolidada: regras de /exercises-qa, coerência sessão/tópico, proibição de treino local/extra sem XP, limite de 20 itens por sessão, validação de changelog de QA com approved: false, e revisão local 150/150 PASS com modelos 9Router ativos.',
    diffs: [
      'Produção /exercises permanece inalterada; nenhuma proposta automática de promoção.',
      'Auditoria de coerência sessão/tópico: nenhum session_topic_semantic_drift nos 150 itens revisados; modelos 9Router apontaram desalinhamento metadado/conteúdo e prompt/resposta no item 1221 (de #1221 “Eu viajo para a cidade.” ↔ “Ich reise nach Berlin.”).',
      'Proibição de treino local, Questão extra, painel frontend-only ou atividade sem XP/progresso; Exercises.jsx e ExercisesQA.jsx sem painéis *Practice.',
      'Recomendação: revisar item 1221 para alinhar “Berlim” ↔ “Berlin” ou generalizar a resposta para “Ich reise in die Stadt.”.',
      'Recomendações visíveis em QA incluem entrada em exercisesQaChangeLog.mjs com approved: false, timestamp DD/MM HH:MM, summary, diffs e approvalPhrase.',
      'Relatório de auditoria cron semanal registrado em reports/polyglot-cron/2026-07-05-run5.md.',
    ],
  },
  {
    id: 'cron-qa-2026-07-03',
    title: 'Cron QA: revisão recente / 9Router vivo / Exercises.jsx limpo (03/07)',
    approved: false,
    approvalPhrase: 'QA aprovado 03/07 HH:MM',
    summary: 'Revisão local recente 150/150 PASS; modelos 9Router (cx/gpt-5.5 e kimi/kimi-k2.6) ativos; 0 entradas pendentes no changelog; Exercises.jsx sem painéis extra/local.',
    diffs: [
      'Revisão local 150/150 PASS via python3 shared/tools/polyglot_agent_review.py --recent 30 --json.',
      'Modelos 9Router online: cx/gpt-5.5 e kimi/kimi-k2.6 retornaram status ok.',
      'Gaps destacados pelos modelos: item 1221 (de #1221) prompt “Eu viajo para a cidade.” vs resposta “Ich reise nach Berlin.”; metadados unit_title “Exponha preferências”/topic “opinião” desalinhados com conteúdo de apresentação/viagem.',
      'Sessão 61 duplicada: índices 1201–1210 e 1211–1220 com question_in_session 1–10 e diálogo idêntico nos índices 1209/1219.',
      'Exercises.jsx sem strings de treino local/Questão extra/painéis *Practice.',
      'Changelog de QA: 0 entradas approved:false.',
    ],
  },
]

export function pendingExercisesQaChanges(entries = exercisesQaChangeLog) {
  return entries.filter((entry) => !entry.approved)
}

export function latestExercisesQaChange(entries = exercisesQaChangeLog) {
  const pending = pendingExercisesQaChanges(entries)
  return pending[pending.length - 1] || null
}
